controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

create_domain:
    path: /api/domains
    controller: App\Controller\DomainController::createDomain
    methods: [POST]